module.exports = {
  BUSINESS_HOURS_START: 8, // 08:00
  BUSINESS_HOURS_END: 18,  // 18:00 (exclusive upper bound)
  CLOSED_WEEKDAYS: [0],    // Sunday
  NAME_MIN_LENGTH: 2,
  PHONE_REGEX: /^0\d{9,10}$/,
  MAX_NOTES_LENGTH: 500,
  FEEDBACK_TYPES: ['COMPLAINT', 'FEEDBACK', 'GENERAL'],
  FEEDBACK_STATUS: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'],
  TEST_DRIVE_STATUS: ['PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED']
};